# Generated by Django 3.0.6 on 2020-05-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to answer')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
